language: generic
sudo: false

addons:
  apt:
    packages:
      - doxygen

script:
  - ./Scripts/build_docs.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: Documentation/Document_Output/html
